<a href="https://colab.research.google.com/github/Gangaithiri241991/Gangaithiri241991/blob/main/welcome_to_the_world_of_programming_language(21_22_sept_evening_batch).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1.Python is high level language (which is closer to human language)
2. Python is an interpreted language
3. it is known for its simplicity and readability
4. Python is being used in many areas like web development , machine learing , data science , app developement , game development

# Important points to remember

#1 . Versatile :  A python is a multiple programming paradigms  which is being used in many areas or field

# Large standard libraray : Python comes with vast standard libraries  that provide various tools and functionality to write the code

# community support : Python has very large community support which help and contribute to the weath  of programming language

Python was created by guido van rossum and it is released in 1991
 based on the funny comedy series named as "monti python flying circus" and he took name from that series and gave a programming language named as python

In [ ]:
Correct_password = 'hari'

Password ''

while

In [ ]:
# java language

public class Helloworld{
    public static void main(Strings [] args){
        System.out.println("hello world")
    }
}

SyntaxError: invalid syntax (<ipython-input-1-ac80c63131d1>, line 3)

In [ ]:
# Python

print("hello world")

hello world


# comments

In [ ]:
# comments in programming language are lines of text that are written to understand by humans .

In [ ]:

# single line comment
a =10  # a is storing value 10
b =20  # b is storing value 20
print(a+b)    # printing addition of two number

30


In [ ]:
# mutiple line comment
"""huefhh
gfiegwuf
wgfiuwgef
gwjfgwjef"""

print("hello world")

hello world


**Variables**

In [ ]:
a =10
print(a)


10


In [ ]:
a

NameError: name 'a' is not defined

In [ ]:
1a = 20
print(1a)

SyntaxError: invalid decimal literal (<ipython-input-4-52c3c741c962>, line 1)

In [ ]:
_a =20
print(_a)

20


In [ ]:
my_76 = 20
print(my_76)

20


rule to declare variable

1>  A variable must start with letter or underscore

2> A variable cannot start with number

3> it can contain alpha-numeric characters

4> A  variable cannot contain  any special characters (@,#,&*)

In [ ]:
_my_var = 20
print(_my_var)


print(type(_my_var))

20
<class 'int'>


# Datatypes :  It is used to tell the type of the data  that  variables are holding

In [ ]:
# Integer : Those are whole numbers such as 1,2,3 ----- n They are having no fractical or decimal


a = 10
print(a)
print(type(a))

10
<class 'int'>


In [ ]:
#  float datatype :   These are the number which are having decimal part as well

x = 10.20
print(x)
print(type(x))

10.2
<class 'float'>


In [ ]:
# String   : "alice"

In [ ]:
x ="alice"
print(x)
print(type(x))

alice
<class 'str'>


In [ ]:
abc ="7876775752375"
print(abc)
print(type(abc))

7876775752375
<class 'str'>


In [ ]:
a ="hello world"
# indexing : to  fetch particular character from the complete string

hello world


In [ ]:
# positive indexing : which always start from left to right and the first character should always be at 0th index
a ="hello world"
   # 012345678910
print(a[0])



h


In [ ]:
a ="hello world"
print(a[8])

r


In [ ]:
# negative indexing   : it always starts from right to left and last character should always be at index no at -1

a  ="superwomen"

print(a[-1])

print(a[-5])




n
w


In [ ]:
a = "multiple string"

#print(a[-4])
#print(a[8])
#print(a[2])
#print(a[0])
print(a[-5])

t


# slicing

In [ ]:
a = "hello world"       #stringname[startindex :endindex+1]

#print(a[0:4+1])
print(a[5:])

print(a[ :6 ])


 world
hello 


In [ ]:
a ="superwomen"

#print(a[-5 : ])

print(a[-10: ])





superwomen


In [ ]:
a = "animal"   # ima
#n to l
print(a[-4:-1])
print(a[-5 :])
#a to l
print(a[-6 :])
print(a[ : ])

print(a[1:])
print(a[0:])
print(a[3:5])

ima
nimal
animal
animal
nimal
animal
ma


In [ ]:
# modify string
a ="overhyped"
print(a.upper())

OVERHYPED


In [ ]:
a ="OVERHYPED"
print(a.lower())

overhyped


In [ ]:
# replace


a ="hello world"
print(a.replace('h','y'))

yello world


In [ ]:
a ="hello  "
b ="learners"
print(a+b)

hello  learners


In [ ]:
a ="hello"
b ="learners"

print(a+" "+b)

hello learners


In [ ]:
a ="overhyped"

print(a.capitalize())

Overhyped


In [ ]:
a ="hello world"
print(a.capitalize())

Hello world


In [ ]:
a ="hello world"
print(a.title())

Hello World


In [ ]:
text = "hello world"

index=text.find(" ")
print(index)

5


In [ ]:

#Suppose if we want letter L from hello

#What will find provide 2 or 3

In [ ]:
# startswith

text ="selephone"
c=text.startswith('tele')
print(c)

True


In [ ]:
# endswith

text ="hello world"

c = text.endswith("hello")
print(c)

False


In [ ]:
text = "Hello world"
print(text.endswith('d'))

True


# Boolean datatype

In [ ]:
print(10 == 4)

False


In [ ]:
print(10>9)

True


In [ ]:
print(18 <= 18)

True


# Sequence datatypes : sequential datatypes refer to a type of data structure that define some sequence or order

#1 list
# 2 tuple
#3 string

# list


# 1 To store mutiple item in a single varibles
#2 list are created with the help of square braces
# 3 List items are having index values
# 4 list elements are mutable (changeable)

In [ ]:
list1  = [1,2,3,4,5,5,6]

print(list1)

[1, 2, 3, 4, 5, 5, 6]


In [ ]:
list2 =['apple','banana','lion']
print(list2)

['apple', 'banana', 'lion']


In [ ]:
list3 =[1,2,3,4,90.0,"strinf"]
print(list3)

[1, 2, 3, 4, 90.0, 'strinf']


In [ ]:
color =["red","blue","green","orange"]

print(color[1])

print(color[-1])



blue
orange


In [ ]:
list1 =[0,2,3,4,5,6,7,8,99,10]

#print(list1[0:7])

print(list1[-7:-1])


[4, 5, 6, 7, 8, 99]


In [ ]:
list1 =['coffee','tea','sugar']


list1[1] ='milk'
print(list1)

['coffee', 'milk', 'sugar']


In [ ]:
list1 =['coffee','tea','sugar']


list1[2] ='salt'
print(list1)

['coffee', 'tea', 'salt']


In [ ]:
# create  a list that will store some details of the students and fetch values that is stored index no 3 , -1 , 8

In [ ]:
list=['stancy', 'mithun','maria','pavan','tiru','martina','swathi','prajwal']
print(list)

In [ ]:
#create a list that will store some details ofthe sutdents
# fetch value in index # 3, -1, 8

student =['opiee',50,'john', 65, 'robert', 100, 'stanley',82,'erica',63]
print (student)

print (student[3])
print (student[-1])
print (student[8])

['opiee', 50, 'john', 65, 'robert', 100, 'stanley', 82, 'erica', 63]
65
63
erica


In [ ]:
student_details = [2105540143,19,"Vimal Shukla","Kumar Partherkar",99,99,720,90,99]
print("Best friend: {}".format(student_details[3]))
print("English marks: {}".format(student_details[-1]))
#Due to the number of items in the list, -1 and 8 refer to the same thing.
print("English marks: {}".format(student_details[8]))

Best friend: Kumar Partherkar
English marks: 99
English marks: 99


In [ ]:
# insert item

list3 =['doramon','shinchan','nobita']

list3.insert(0,"Ben ten")
print(list3)


['Ben ten', 'doramon', 'shinchan', 'nobita']


In [ ]:
list = [12,34,45,67,34]
print(list)

[12, 34, 45, 67, 34]


In [ ]:
# append

list1 =['i3r',9,8,7,'oi']
list1.append('uiiy')
print(list1)

['i3r', 9, 8, 7, 'oi', 'uiiy']


In [ ]:
# extent method
list1 =['red','liouf','r3y']
list2 =[1,2,3,4,5,6,7]


list1.extend(list2)
print(list1)
print(list2)

list2.extend(list1)
print(list2)

['red', 'liouf', 'r3y', 1, 2, 3, 4, 5, 6, 7]
[1, 2, 3, 4, 5, 6, 7]
[1, 2, 3, 4, 5, 6, 7, 'red', 'liouf', 'r3y', 1, 2, 3, 4, 5, 6, 7]


In [ ]:
list3 =[1,3,4,5,6,6,7.0]
list4 =['peie','opi','iwo']

list4.extend(list3)
print(list4)

['peie', 'opi', 'iwo', 1, 3, 4, 5, 6, 6, 7.0]


In [ ]:
list3 =[1,3,4,5,6,6,7.0]
list3.remove(3)

print(list3)



[1, 4, 5, 6, 6, 7.0]


In [ ]:
list2 =['you','me','us']
list2.remove(list2[0])
print(list2)

['me', 'us']


In [ ]:
list1 =['iouer',8,8943,3434,434]
list1.clear()
print(list1)

[]


In [ ]:
list2 =['you','me','us']
del list2
print(list2)

NameError: name 'list2' is not defined

In [ ]:
# pop

list1 =['opo','apolo','ur','oru',7]
list1.pop(1)
print(list1)

['opo', 'ur', 'oru', 7]


In [ ]:
list1 =['ud','o','ii']
print(list1)

['ud', 'o', 'ii']


In [ ]:
Qyei = ['jay','ajay','git','amar','amay']
print(Qyei)

['jay', 'ajay', 'git', 'amar', 'amay']


In [ ]:
# sort
#ascending
list1 =[90,89,45,56,45,34,23]
list1.sort()
print(list1)

[23, 34, 45, 45, 56, 89, 90]


In [ ]:
#descending order
list1 =[12,34,56,67,78,89,100]
list1.sort(reverse=True)
print(list1)

[100, 89, 78, 67, 56, 34, 12]


In [ ]:
#finding index value of particular  value
fruits  =['pineaple','grapes','oranges']

print(fruits.index('pi'))

ValueError: 'pi' is not in list

**Tuple**
1> It is used to store multiple items in a single variable

2> A tuple is a collection of items which is ordered and immutable(unchangable)


3> we use () to create a tuple

In [ ]:
tuple1 =('uefugfe',90,90.0,True)
print(tuple1)

('uefugfe', 90, 90.0, True)


In [ ]:
tuple1 =('uefugfe',90,90.0,True)
print(tuple1[1])

90


In [ ]:
tuple = ("apple","kiwi",23,566,7,90.0)

print(tuple)
# fetch from apple to 7
# fetch from 90.0 to kiwi

('apple', 'kiwi', 23, 566, 7, 90.0)


In [ ]:
print(tuple[4]) #returns 7 amrit
print(tuple[0:7])  #pransana


7
('apple', 'kiwi', 23, 566, 7, 90.0)


In [ ]:
stancy=('apple','kiwi',23,566,7,90.0)
print(stancy[0:])
print(stancy[-1:-6:-1])

('apple', 'kiwi', 23, 566, 7, 90.0)
(90.0, 7, 566, 23, 'kiwi')


In [ ]:
tuple1 = ("apple","Kiwi",23,566,7,90.0)

print(tuple1[0:5])

print(tuple1[-1:-6:-1])


('apple', 'Kiwi', 23, 566, 7)
(90.0, 7, 566, 23, 'Kiwi')


In [ ]:
tuple1 = ("apple","kiwi",23,566,7,90.0)


# fetch from apple to 7
# fetch from 90.0 to kiwi
print(tuple1[0:5])
print(tuple1[-1:-6:-1])

"""output
======
('apple', 'kiwi', 23, 566, 7) (90.0, 7, 566, 23, 'kiwi')"""

('apple', 'kiwi', 23, 566, 7)
(90.0, 7, 566, 23, 'kiwi')


"output\n======\n('apple', 'kiwi', 23, 566, 7) (90.0, 7, 566, 23, 'kiwi')"

In [ ]:
 # to update a tuple


x = ('let',',me','finish')
print(x)
y=list(x)
print(y)
y[1] ='you'
print(y)

x=tuple(y)
print(x)





('let', ',me', 'finish')
['let', ',me', 'finish']
['let', 'you', 'finish']
('let', 'you', 'finish')


In [ ]:
def my_function():
  print("hello good evening")
my_function()

hello good evening


In [ ]:
def area(l,w):
  print(l*w)
area(5,6)

30


In [ ]:
pip install numpy


In [ ]:
x = ('let',',me','finish')



y=list(x)
print(y)
y[1] ='you'
print(y)
x =tuple(y)
print(x)

print(type(x))


,me
('let', ',me', 'finish')
['let', ',me', 'finish']
['let', 'you', 'finish']
('let', 'you', 'finish')
<class 'tuple'>


In [ ]:
country =('france','germany','japan')
country[1]='PARIS'
print(country)


TypeError: 'tuple' object does not support item assignment

In [ ]:
x =(1,2,3,4,55,67,8)
list_updated=list(x)
print(list_updated)
list_updated.remove(8)
print(list_updated)

x=tuple(list_updated)
print(x)



[1, 2, 3, 4, 55, 67, 8]
[1, 2, 3, 4, 55, 67]
(1, 2, 3, 4, 55, 67)


In [ ]:
# create a tuple which will store some strings values and then  pop the 2 index value from the tuple


In [ ]:
#shivam
tuple1=('a','b','c','d','e')

y=list(tuple1)

print(y)

y.pop(2)

tuple1=tuple(y)

print(tuple1)


['a', 'b', 'c', 'd', 'e']
('a', 'b', 'd', 'e')


In [ ]:
#amrit
mt = ("My","name","is","John","Roe")
mtlst = list(mt)
print("Removed {}".format(mtlst.pop()))
print("Mtlst (list of mt): {}".format(mtlst))
mt = tuple(mtlst)
print("Final tuple: {}".format(mt))

Removed Roe
Mtlst (list of mt): ['My', 'name', 'is', 'John']
Final tuple: ('My', 'name', 'is', 'John')


In [ ]:
#om
tupple2 = ('apple','banana','cherry','kiwi','orange')
print(tupple2)
print(tupple2[2])

x = list(tupple2)
print(x)
x.pop(2)
print(x)
tupple2 = tuple(x)
print(tupple2)

('apple', 'banana', 'cherry', 'kiwi', 'orange')
cherry
['apple', 'banana', 'cherry', 'kiwi', 'orange']
['apple', 'banana', 'kiwi', 'orange']
('apple', 'banana', 'kiwi', 'orange')


In [ ]:
stancy=('America','London','Scotland','Amsterdam')
print(stancy)
stan=list(stancy)
print(stan)
stan.pop()
print(stan)
stancy=tuple(stan)
print(stancy)


('America', 'London', 'Scotland', 'Amsterdam')
['America', 'London', 'Scotland', 'Amsterdam']
['America', 'London', 'Scotland']
('America', 'London', 'Scotland')


In [ ]:
tupple2 = ('cry','sad','laugh','okay','null')
print(tupple2)
print(tupple2[2])

x = list(tupple2)
print(x)
x.pop(2)
print(x)
tupple2 = tuple(x)
print(tupple2)

('cry', 'sad', 'laugh', 'okay', 'null')
laugh
['cry', 'sad', 'laugh', 'okay', 'null']
['cry', 'sad', 'okay', 'null']
('cry', 'sad', 'okay', 'null')


In [ ]:
tuple1 =(1,2,3,4,55)
del tuple1

print(tuple1)


NameError: name 'tuple1' is not defined

In [ ]:
tuple1 =(1,2,3,4,55)
tuple2=tuple1.clear()

AttributeError: 'tuple' object has no attribute 'clear'

In [ ]:
tuple1 =(1,2,3,4,5,"mohan","ours")
print(tuple1)

updated_list =list(tuple1)
print(updated_list)

updated_list[5] ='you'
print(updated_list)

tuple1=tuple(updated_list)
print(tuple1)



(1, 2, 3, 4, 5, 'mohan', 'ours')
[1, 2, 3, 4, 5, 'mohan', 'ours']
[1, 2, 3, 4, 5, 'you', 'ours']
(1, 2, 3, 4, 5, 'you', 'ours')


In [ ]:
class Sum:
  def s1(self,a=0,b=0):
    self.a=a
    self.b=b

   print(self.s2)

  def s2(self,d=0,e=0,c=0):
    self.c=c
    self.d=d
    self.e=e
    print(self.c + self.d + self.e)

x=Sum()
x.s2(1,2,3,4,5)

IndentationError: unindent does not match any outer indentation level (<tokenize>, line 6)

22/09/2024 ---- Topic
Summary session I so far 9/22 - sunday
===============================
Boolean data type
Sequential data types
List, tuple, string
List functions


Summary session II
=================
List functions
Tuple
It is

Created with round Brackets, immutable and cant be updated


Print tuble

Using index in forward and reversing order


Replace entire tuple using tuple()

Using another list and modify list and xfer modified list back into tuple using tuple()


Exercise

Create a tuple and modify tuple value using a list variable and pop


Del

Delete tuple variable


Clear

Cant be used as it is immutable

eg:  tuple1.clear() - not allowed as valid attribute





Sort

Order the elements in a list variable based upon value


Sort descending

Order the value within a variable using reverse==true


Index

Get the index of the value position in the variable

Append

Add new value at the end of list values

Insert

- insert a new value into an existing list at indexed value


Del   

- entire variable removal


Remove

- value removal within the existing values in the list variable


Pop

- remove a particular indexed value within a list variable


Extend

- bring another list values into another list variable


Clear

- clear values inside the variable



In [ ]:
thiset ={1,2,2,3,4,5,6,7}
thiset

thiset.remove(1)

print(thiset)

{2, 3, 4, 5, 6, 7}


In [ ]:
thiset.remove(1)

KeyError: 1

#**sets**  : It is used to store multiple items in a single varaible

#1 . It is unordered(order is not defined)
#2. It is unchangable (once the set has been  created you cannot the sets but there are method to add or remove the items that is present in your sets)
#3. A sets is a unindexed (it is not having any indeixing method)
#4 . sets donot allow duplicated values

# 5   sets is created using{}

In [ ]:
set1 ={'apple','lion','cherry','True',3}
print(set1)

{'apple', 'True', 3, 'lion', 'cherry'}


In [ ]:
set1 ={"true",2,3,4,'abc','xyz',1,False}
print(set1)

{False, 1, 2, 3, 4, 'xyz', 'true', 'abc'}


In [ ]:
set2 ={1,2,3,4,4,5,56,6,7,7,8,8,9,9,9,0,0,10}
print(set2)

{0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 56}


In [ ]:
set2 ={2,4,4,6,8,7,9,10}
print(set2)

{2, 4, 6, 7, 8, 9, 10}


In [ ]:
set3 ={True,2,3,4,45,'komal','liyra',1,False,0}

print(set3)

{False, True, 2, 3, 4, 'komal', 'liyra', 45}


In [ ]:
# acessa item
set2 ={1,1,34,455,5}

In [ ]:
#add item
set1 ={1,2,'yellow','kiran'}
set1.add("orange")
print(set1)

{1, 2, 'orange', 'kiran', 'yellow'}


In [ ]:
set1 ={1,2,'yellow','kiran'}

set2 = {1,2,3,434,4,556}

set1.update(set2)

print(set1)

print(set2)

{1, 2, 3, 4, 556, 434, 'kiran', 'yellow'}
{1, 2, 3, 4, 434, 556}


In [ ]:
"""set1 ={1,2,'yellow','kiran'}

set1.append('louo')
print(set1)""

AttributeError: 'set' object has no attribute 'append'

In [ ]:
set1 ={1,2,'yellow','kiran'}

set1.remove('kiran')
print(set1)

{1, 2, 'yellow'}


In [ ]:
set1 ={1,2,3,4,5}
set2 ={3,4,5,6,7}

print(set1.union(set2))

{1, 2, 3, 4, 5, 6, 7}


In [ ]:
# common items
set1 ={1,2,3,4,5}
set2 ={3,4,5,6,7}
print(set1.intersection(set2))

{3, 4, 5}


In [ ]:
set1={1,2,3,4}
set2={3, 4, 5,6}
#print(set.union(set2))

print(set1.union(set2))
#print(set1)

{1, 2, 3, 4, 5, 6}


In [ ]:
"""set1={1,2,3,4}
set2={3, 4, 5,6}
set3=set1+set2
print(set3)"""

'set1={1,2,3,4}\nset2={3, 4, 5,6}\nset3=set1+set2\nprint(set3)'

In [ ]:
set1 ={1,2,3,4,5,66,78}
set1.pop()
print(set1)



{2, 3, 4, 5, 66, 78}


In [ ]:
set1 ={1,2,3,4,5,66,78}

set1.clear()
print(set1)

set()


In [ ]:
set1 ={1,2,3,4,5,66,78}

del set1

print(set1)


NameError: name 'set1' is not defined

In [ ]:
set5 ={1,2,3,4,5,66,90}
set2 ={6,20,33,4,5,66,78}
set3 ={6,20,33,89,90,7}


set4=set5.intersection(set2,set3)
print(set4)

set()


In [ ]:
set1 ={1,2,3,4,5,66,90}
set2 ={6,20,33,4,5,66,78}
set3 ={6,20,33,89,90,7,4,5}


set4=set1.intersection(set2,set3)
print(set4)

{4, 5}


In [ ]:
set1={1,2,3,4,5,66,78}

set2={1,2,3,4,4,5,56,6,7,7,8,9,9,9,0,0,10}

set3={4,24,5,700}
print(set1)
print(set2)
print(set3)

set4=set1.union(set2,set3)
print(set4)

{1, 2, 3, 4, 5, 66, 78}
{0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 56}
{24, 5, 700, 4}
{0, 1, 2, 3, 4, 5, 66, 6, 7, 8, 9, 10, 78, 24, 56, 700}


In [ ]:
set1={1,2,3,4,5,66,78}
set2-{7,8,9,10,11,15,5,78}
set3={90,89,45,77,5,78}
set4=set1.intersection(set2,set3)
print(set4)

{5, 78}


#**Dictionary**

In [ ]:
# a dictionary is used to store the data as a key -value pair



In [ ]:

# duplicate keys are not allowed but the values should be duplicate
dict1 ={
    "name":"roopneet",
    "age": 32,
    "gender":"female"
    }


    # }

print(dict1)

{'name': 'roopneet', 'age': 32, 'gender': 'female'}


In [ ]:
# create a dictionary which is having key values   for some brands and their associated value

In [ ]:
myDict = {
    "Name" : "Infosys",
    "CEO" : "Sudha Murty",
    "Net worth" : 887693900,
    "Profit" : 987
}

In [ ]:
dict1 = {'Gucci':'bags','puma':'shirts','Addidas':'shoes'}
print(dict1)

{'Gucci': 'bags', 'puma': 'shirts', 'Addidas': 'shoes'}


In [ ]:
dict1 = {
    "brand": "lambo",
    "color": "red",
    "model": "2001"
}
print(dict1)


{'brand': 'lambo', 'color': 'red', 'model': '2001'}


In [ ]:
#create a dictionary which is having key values for some brands and their associated value
dict2={
    'apple':'iphone',
    'samsung':'galaxy',
    'lg':'tv'
}
print(dict2)
#


{'apple': 'iphone', 'samsung': 'galaxy', 'lg': 'tv'}


In [ ]:
dict2={
    'apple':'iphone',
    'samsung':'galaxy',
    'lg':'tv'
}
print(dict2['samsung'])

galaxy


In [ ]:
dict3 ={
    "brand":"ford",
    "model":"mustang",
   "year":1977,
   "year":1990

}
print(dict3)

{'brand': 'ford', 'model': 'mustang', 'year': 1990}
3


In [ ]:
dict3 = {
       "samsung" : "Galaxy",
       "apple": "iphone",
       "Realme" : 13

   }

print(dict3)

{'samsung': 'Galaxy', 'apple': 'iphone', 'Realme': 13}


In [ ]:
# create a dictionary that storing data  regarding any student record and then fetch the marks and percentage

In [ ]:
dict3 = {
    "name": "mohan",
    "class": "12th Grade",
    "marks": {
        "Math": 85,
        "Science": 90,
        "English": 78,
        "History": 88,
        "Physical Education": 92
    }
}
print(dict3)

{'name': 'mohan', 'class': '12th Grade', 'marks': {'Math': 85, 'Science': 90, 'English': 78, 'History': 88, 'Physical Education': 92}}


In [ ]:
dict1={"name":"john","marks":"99","percentage":"99%"}
print(dict1)
print(dict1["marks"])
print(dict1['percentage'])

{'name': 'john', 'marks': '99', 'percentage': '99%'}
99
99%


In [ ]:
# create a dictionary that storing data regarding anny student record and then fetch the marks and percentage

stud_dict={
      'name':'opiee',
      'class':'pyhton',
      'marks':34,
      'percentage':'50%'
}
print(stud_dict)
print(stud_dict['marks'])
print(stud_dict['percentage'])
#
print(stud_dict['marks'])
print(stud_dict['percentage'])
#

{'name': 'opiee', 'class': 'pyhton', 'marks': 34, 'percentage': '50%'}
34
50%
34
50%


In [ ]:
stud_dict={
      'name':'opiee',
      'class':'pyhton',
      'marks':34,
      'percentage':'50%'
}


print(stud_dict.get('percentage'))

print(stud_dict.get('marks'))

50%
34


In [ ]:
stud_dict={
      'name':'opiee',
      'class':'pyhton',
      'marks':34,
      'percentage':'50%'
}

print(stud_dict.keys())

dict_keys(['name', 'class', 'marks', 'percentage'])


In [ ]:
stud_dict={
      'name':'opiee',
      'class':'pyhton',
      'marks':34,
      'percentage':'50%'
}
print(stud_dict.values())


dict_values(['opiee', 'pyhton', 34, '50%'])


In [ ]:
stud_dict={
      'name':'opiee',
      'class':'pyhton',
      'marks':34,
      'percentage':'50%'
}

print(stud_dict.items())

dict_items([('name', 'opiee'), ('class', 'pyhton'), ('marks', 34), ('percentage', '50%')])


In [ ]:
# new key value


dict1 ={
    "brand":"ford",
    "model":"mustang",
    "year":1964
}


dict1.update({"color":"white"})

print(dict1)

{'brand': 'ford', 'model': 'mustang', 'year': 1964, 'color': 'white'}


In [ ]:
dict2 ={
    'color':'black',
    'model':1990,
    'speed':788
}

dict2['hipe'] ='30km'

print(dict2)

{'color': 'black', 'model': 1990, 'speed': 788, 'hipe': '30km'}


In [ ]:
dict3 ={
    'cartoons':'pogo tv',
    'series':'netflix',
    'ratings':'above 10+'
}

dict3.pop('ratings')

print(dict3)





{'cartoons': 'pogo tv', 'series': 'netflix'}


In [ ]:
dict3 ={
    'cartoons':'pogo tv',
    'series':'netflix',
    'ratings':'above 10+'
}
dict3.popitem()
print(dict3)

{'cartoons': 'pogo tv', 'series': 'netflix'}


In [ ]:
dict3 ={
    'cartoons':'pogo tv',
    'series':'netflix',
    'ratings':'above 10+'
}
dict3.clear()
print(dict3)

{}


In [ ]:
dict3 ={
    'cartoons':'pogo tv',
    'series':'netflix',
    'ratings':'above 10+'
}

del dict3
print(dict3)

NameError: name 'dict3' is not defined

In [ ]:
dict3 ={
    'cartoons':'pogo tv',
    'series':'netflix',
    'ratings':'above 10+'
}

del dict3['series']
print(dict3)

{'cartoons': 'pogo tv', 'ratings': 'above 10+'}


**operators**

In [ ]:
# operators are used to perform some operations on variables and values


# **arthemetic** **operator** :

In [ ]:
a = 10
b = 20
print(a+b)
print(a-b)
print(a*b)
  print(a/b)
print(a//b) # floor division   # quotient
print(a%b)   # modulus

print(a//b)   # remove the decimal part and provide only integer output

30
-10
200
0.5
0
10
0


In [ ]:
# assignment operator

# it is used to assign values to  variable

a = 10
print(a)

10


In [ ]:
# addition assignment

x = 5
x += 3    #  x = x+3
print(x)




8


In [ ]:
# substraction assignment


x = 10
x -= 8
print(x)

2


In [ ]:
# perform division , modulus and  floor division


In [ ]:
a= 10
b = -8
a /= b
print(a)


-1.25


In [ ]:
a = 10
b = -8
print(a/b)
print(a//b)
print(a+b)

-1.25
-2
2


In [ ]:
a = 15
b = 4

division = a / b
modulus = a % b          # Modulus (remainder)
floor_division = a // b

print(f"Division: {division}")
print(f"Modulus: {modulus}")
print(f"Floor Division: {floor_division}")

Division: 3.75
Modulus: 3
Floor Division: 3


In [ ]:
a = 10
b = -8
a /= b
print(a)
a = 10
a %= b
print(a)
a = 10
a //= 10
print(a)

-1.25
-6
1


# **Comparison** **operator**

In [ ]:
x = 10
y = 20


print(x == y)



False


In [ ]:
#
x = 20
y = 20

print(x != y)

False


In [ ]:
print(x <= y)

True


# **logical** **operator**

In [ ]:
# AND
# OR
# NOT

In [ ]:
1 CONDITION AND 1 CONDITION   # AND  will give output as true when both the condition are true otherwise it will give false
2. Condition1 or condition 2   # or will give output as true if any of the condition is true other wise if both the conditions are false
# only you will get output as false

3 not Condition1 and condition 2  #  it is used to reverse the output

In [ ]:
x = 5

print(x>3 and x<10)

False


In [ ]:
x  = 10
print(x>20 or  x<20)

True


In [ ]:
 x  = 10
print(not(x>20 or  x<20))

False


# Membership operator

# to Check wheather a particular item in present in sequence or not

In [ ]:
# IN   # to check an item is present  or not

In [ ]:
# NOT IN   # to check wheather an item is not present in sequence

In [ ]:
list1 =[1,2,3,4,5,'oefo']
print(1  in list1)

True


In [ ]:
list2 =['jihdi','ydi','hello']

print('hello' not in list2)

False


# conditional statements

# if statement

In [ ]:
# if statement will work only if you condition is true  otherwise you wont be able to get any output

In [ ]:
a = 10
b = 30

if a>b:

  print('yes , your number is greater')



In [ ]:
a = int(input('enter the first number'))
b = int(input('enter the second number'))





if a>b:
  print("you condition is true")


enter the first number5
enter the second number3
<class 'int'>
you condition is true


In [ ]:
# ask the user to enter the age , check wheather the age is greater than equal to 18 , if condition is true then you have to pass the statement that
# you are willing to vote

In [ ]:
a=int(input("enter the age"))


if a>18:
    print('yes allowed to vote')
if a<18:
    print("not allowed to vote")

enter the age78
yes allowed to vote


In [ ]:
age = 18

if age >= 18:
    print("You are eligible to vote.")

You are eligible to vote.


In [ ]:
a=int(input('enter your age:'))
if a>=18:
  print('you can vote')

enter your age:76
you can vote


In [ ]:
Age=int(input("please enter your age:"))
if Age>18:
    print("You can vote")
else:
    print("You cannot vote")


please enter your age:54
You can vote


In [ ]:
age = int(input("Enter the age: "))
if age >= 18:
  choice = input("Would you like to vote? (Yes/No): ")
  if choice.lower() == "yes":
       print("Congratulations! You can vote now!")
  else:
      print("Thanks for your choice!")
else:
    print("You are ineligible to vote!")

Enter the age: 55
Would you like to vote? (Yes/No): no
Thanks for your choice!


In [ ]:
age = int(input('Enter Age'))
if age >= 18:
  print('You are willing to vote')
else:
  print('You are not eligible to vote')


Enter Age54
You are willing to vote


In [ ]:
# exercise 1 - opiee / om

age = int(input('enter the age of the person:  '))

print(type(age))
if age >= 18:
  print('person is eligible to vote')
else:
  print('person is not eligible to vote')

print('end'  )

enter the age of the person:  4
<class 'int'>
person is not eligible to vote
end


#**else** **statement**

In [ ]:
age = int(input("enter the age: "))


if age >= 18:
    print("you are willing to vote")

else:  # when your condition will become false this else part will work and provide the output
  print("you are not eligible to vote")


enter the age: 3
you are not eligible to vote


# even or not

In [ ]:
num = int(input("enter any number"))


if num % 2 == 0:
  print("yes the number is even")

else:
  print("number is not even")

enter any number13
number is not even


elif : else if
To check multiple conditions

In [ ]:
marks = int(input("enter the your marks "))

if marks >= 90:
  print("congraculation you got Grade A")

elif marks >= 75:
  print("you got grade B")

elif marks >= 65:
  print("you got grade C")



else:

  print("you got less marks , you have to again reappear for the exam")

enter the your marks 78
you got grade B


In [ ]:
# ask the user to enter temperature and if temperature is greater than 30 , print its very  hot , again check temperature is greater 25 then
# its moderate and similar  way put one more condition to just give the information about temperature

In [ ]:
# ask the user to enter the temperatur, check if temp is greater than 30 then say its very hot and
# if temperatur is less than 25 then say it is very cold and between temperature, say it is normal room temperature

temp = int(input('enter the temperature:  '))

if temp > 30:
  print('its very hot')
elif  30 >temp>24:
  print('its very cold')
else:
  print('its normal room temperature')

print('end of code')

enter the temperature:  26
its very cold
end of code


In [ ]:
temperature = float(input("Please enter the temperature in Celsius: "))

if temperature > 30:
    print("It's very hot.")
elif temperature > 25:
    print("It's moderate.")
else:
    print("The temperature is cool.")

Please enter the temperature in Celsius: 23
The temperature is cool.


In [ ]:
bmi = 28.0

if bmi <18.5:
  print("underweight")
elif  18.4<=bmi<24.9:
  print("normal weight")

elif  25<=bmi<29.9:
  print("overweight")


else:
  print("obsesity")

overweight


In [ ]:
# create a program to check a number is postive and even

num = int(input("Enter a number: "))
if num>0:
    print("{} is positive...".format(num))
    if num%2 == 0:
        print("...{} is also even.".format(num))
    else:
        print("...but {} is not even.".format(num))
else:
    print("{} is negative or 0.".format(num))

Enter a number: 34
34 is positive...
...34 is also even.


In [ ]:
num = int(input("enter the number : "))

if num % 2 == 0:
    print("number is positive")

else:
    print("number is even")

enter the number : 45
number is even


In [ ]:
number = int(input("Enter a number:"))
if number > 0:
    if number % 2 == 0:
        print("Positive and even.")
    else:
        print("Positive but not even.")
else:
    print("Not positive.")

Enter a number:34
Positive and even.


In [ ]:
n = int(input("Enter a number: "))

# Check if the number is positive and even
if n > 0 and n % 2 == 0:
    print(f"{n} is positive and even.")
elif n > 0:
    print(f"{n} is positive but not even.")
else:
    print(f"{n} is not positive.")


Enter a number: 4
4 is positive and even.


In [ ]:
#take a number and check if it is postive or negative and then if positive check if it is even or not
#cody by om/opiee
num1 = int(input('enter the number:  '))

if num1 > 0:
  print('number is positive')
  if num1 % 2 == 0:
    print('number is even')
  else:
    print('number is odd')

elif num1 < 0:
  print('number is negative')
else :
  print('number is zero')

print('end of code')

enter the number:  3
number is positive
number is odd
end of code


In [ ]:
Num = int(input("Enter a number"))
if Num>0 :
   print("Number is positive")
   if Num%2==0 :
      print("Number is Even")
   else :
      print("Number is ODD")

else :
    print("Number is negative")

Enter a number65
Number is positive
Number is ODD


In [ ]:
num=int(input("Enter the number:"))
if num>0:
    print("Positve")
elif num%2==0:
    print("Even")
else:
    print("Neither positive nor even")

Enter the number:5
Positve


In [ ]:
check the number is postive  and even nmber

In [ ]:
num = int(input("enter the number : "))

if num>0 and  num%2 ==0:
  print("number is positive and even")


else:
  print(" your condition is false")


enter the number : 6
number is positive and even


In [ ]:


# create a program to check a number is positive and even

num = int(input( 'Enter any number '))

if num >0 and num%2==0 :
  print(' Number is postive and even')
else:
  print ('Input again')

Enter any number 6
 Number is postive and even


# **Looping** **statments**

In [ ]:
# for loop
# while loop

In [ ]:
for variable in sequence or range():


In [ ]:
fruits =['apple','banana','orange','pineapple']


for var in fruits:
  print(var)

apple
banana
orange
pineapple


In [ ]:
x ="hello"

for i in x:
  print(i)

h
e
l
l
o


In [ ]:
# range


for i in range(1,5+1):      # for x in range(start value : end value+1)
  print(i)

1
2
3
4
5


In [ ]:
for x  in range(1,101):
  print(x)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100


In [ ]:
#  create a list which is storing integer value in that list you  have to fetch only even numbers

In [ ]:
numbers = [12, 5, 8, 17, 24, 9, 6, 13, 20]
even_numbers = [num for num in numbers if num % 2 == 0]
print("Even numbers:", even_numbers)

Even numbers: [12, 8, 24, 6, 20]


In [ ]:
list1=[1,2,3,4,6,8,10,12,14,16,18]
for i in list1:
  if i%2==0:
    print(i,"number is even")

2 number is even
4 number is even
6 number is even
8 number is even
10 number is even
12 number is even
14 number is even
16 number is even
18 number is even


In [ ]:
nums = [int(i) for i in input("Enter some numbers seperated by commas (like 1,2,3): ").split(',')]
for i in nums:
    if i%2 == 0:
        print("{} is an evem number".format(i))
    else:
        print("{} is an odd number".format(i))

Enter some numbers seperated by commas (like 1,2,3): 1,2,3,4,5
1 is an odd number
2 is an evem number
3 is an odd number
4 is an evem number
5 is an odd number


In [ ]:
i = int(input("Enter any number "))

for x in range(i):
  if x%2==0:
    print(x)



Enter any number 6
0
2
4


In [ ]:
numbers =[1,2,3,4,5,6,7,8]

for num  in numbers:
  if num %2 != 0:
    print(num)



1
3
5
7


# **while** **loop**

In [ ]:
i =1
while i<=6:
  print(i)
  i+=1

1
2
3
4
5
6


In [ ]:
i = 2
while i <= 20:
  print(i)
  i+=1

2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20


In [ ]:
i = 0
while i<=4:
  print(i,"hello")
  i+=1

0 hello
1 hello
2 hello
3 hello
4 hello


In [ ]:
#add attempt count to above and once it is 3 times, then lock the account

correct_password = "python"
password = ' '
attempt_count = 0
while (password != correct_password):
    password = input('Enter the currnet password:   ')
    attempt_count += 1
    if attempt_count == 3:
      print('account locked')
      break
print('acess granted')
print('end of code')

Enter the currnet password:   hiew
Enter the currnet password:   hihef
Enter the currnet password:   hihfewf
account locked
acess granted
end of code


In [ ]:

correct_password = "python"

password = " "

while password != correct_password:
    password = input("enter correct_password") # indented this line of code
    if password == correct_password:
        print("access granted")
    else:
        print("access denied")

access denied


# fUNCTIONS :  it  is a resuable block of code that is being repeated multiple times whenever you are  going to call it

In [ ]:
# write once and  run many times
def my_function():
  print("hello from function")

my_function()
my_function()

my_function()


hello from function
hello from function
hello from function


In [ ]:
def print_date():
  print("today's date is 05-10-2024")

print_date()
print_date()

today's date is 05-10-2024
today's date is 05-10-2024


In [ ]:
def my_function():
  print("hello from function")

my_function()

hello from function


In [ ]:
#  create a fuction which will print good evening

In [ ]:
# Function
# from opiee/om

# create a function which will print good evening

def greet():
  print('good evening')

greet()

good evening


In [ ]:
def my_func():
    print("Good Evening")
my_func()

Good Evening


In [ ]:
def good_evening(name="Someone"):
    return f"Good evening {name}!"
print(good_evening(name="Amrit"))

Good evening Amrit!


In [ ]:
def morning_call():
  print("good evening")

morning_call()

good evening


# argument :   information that is being passed to your function

In [ ]:
def my(name, rollno):

  print(name, rollno)



my("om",99)
my("riya",7)

om 99
riya 7


In [ ]:
# create a  function which will calculate the area of rectange


area = l*w




In [ ]:
def area (l,b):
    print(l*b)
area(5,5)



25


In [ ]:
def area(length=20,breadth=25):
    return length * breadth
print(area(int(input("Enter length: ")), int(input("Enter breadth: "))))

Enter length: 6
Enter breadth: 45
270


In [ ]:
# f-string

name = "huhg"
age = 56

greeting = f"hello , my name is {name} and age is{age}"
print(greeting)



hello , my name is huhg and age is56


In [ ]:
# function without return

def add_number(a,b):
   result = a+b
   print(result)


print(add_number(12,34))
print(add_number(12,34))


46
None
46
None


In [ ]:
# function with return

def add_number(a,b):
 result = a+b
 return result

add_number(12,34)

print(add_number(12,34))

46


In [ ]:
def greet(name):
  result = f'good evening {name}'
  return result
  #print('good evening', name)

print(greet('om'))

print(greet ('roopneet'))
greet ('welcome to october')

greet('om')

greet ('roopneet')
greet ('welcome to october')

good evening om
good evening roopneet


'good evening welcome to october'

In [ ]:
# create a  function which will return  multiplication of 3 numeber

In [ ]:
#create a function which will return multiplication of 3 number
#code by om/opiee

def multi3(a,b,c):
  result = a*b*c
  return result

print(multi3(1,2,3))
print(multi3(2,3,4))
print(multi3(3,4,5))

6
24
60


In [ ]:
def mul(a,b,c):
  return a*b*c
print(mul(2,3,4))

24


In [ ]:
# arbitary arguments   :   while calling the function  you can provide n numbers of values



def family_members(*members):
  return members

print(family_members("alice","riva","udit","kiw","iyf","ufef","uug","u8ugi","hiugi"))

('alice', 'riva', 'udit', 'kiw', 'iyf', 'ufef', 'uug', 'u8ugi', 'hiugi')


In [ ]:
# create a function  which take kids as a arbitary argument and  while  calling the function print only  2 second child

In [ ]:
# create a function which take kids as a arbitary argument
# while calling the function print only 2 second chiled
# code by om/opiee

def kids_name(*names):
  print(names[2-1])

kids_name('om','roopneet','sri','raja')

roopneet


In [ ]:
def second_child(*kids):
   return "2 nd  child is ",kids[1]

print(second_child("Chikoo","Bunty")) #Normal


('2 nd  child is ', 'Bunty')


In [ ]:
# keywords arguments

def hello(child1 , child2 , child3):
  return f"{child2},{child1},{child3}"

hello("oriya","om","keshav")

'om,oriya,keshav'

In [ ]:
#  create a  function   named  as described_pet and provide some parameter that will best decribe your pets

In [ ]:
def describe_pet(pet_name, animal_type, age, color, breed):
    description = f"{pet_name} is a {age}-year-old {color} {animal_type} of the {breed} breed."
    return description
description = describe_pet("Bella", "dog", 3, "golden", "Golden Retriever")
print(description)

Bella is a 3-year-old golden dog of the Golden Retriever breed.


In [ ]:
def described_pet(name,des):
  return(f"{name},{des}")
print(described_pet(name="cat",des="color of my cat is white"))

cat,color of my cat is white


In [ ]:
def described_pet (breed,age,weight):
    return(f"{breed},{age},{weight}")
print(described_pet(breed="husky",age = 8, weight = 20))

husky,8,20


In [ ]:
def described_pet(name="Pet",species="Pet",scientific_name="Pet",endangered=False,description="A cute, very-friendly creature that you'll love!"):
    describer = f"Name: {name}\nSpecies: {species}\nScientific Name: {scientific_name}\nEndangered: {endangered}\nDescription:\n{description}"
    return describer
print(described_pet())

Name: Pet
Species: Pet
Scientific Name: Pet
Endangered: False
Description:
A cute, very-friendly creature that you'll love!


In [ ]:
def described_pet(petname1,petname2,petname3,petname4):
  return f"{petname1},{petname2},{petname3},{petname4}"

described_pet("cat","dog","elephant","cow")

'cat,dog,elephant,cow'

In [ ]:
# add two numbers ,  num1 and num2(input from user ) and call it


def add_two_num():
  num1 = float(input("enter the num1"))
  num2 = float(input("enter the num2"))
  return f"the addition of two   numbers are{num1} + {num2} ={num1+num2}"


print(add_two_num())

enter the num167
enter the num276
the addition of two   numbers are67.0 + 76.0 =143.0


In [ ]:
import re
def add_input():
    x = input("Enter a number: ")
    y = re.findall(r'\D',x)
    if len(y) != 0:
        return "Invalid input"
    z = input("Enter another number: ")
    a = re.findall(r'\D',z)
    if len(a) != 0:
        return "Invalid input"
    return int(x) + int(z)
print(add_input())

Enter a number: 67
Enter another number: 76
143


In [ ]:
def add (a,b):
    return a+b
print(add(a = int (input("number 1: ")),b = int (input("number 2:"))))

number 1: 7
number 2:2
9


In [ ]:
def addition():

    a = (input("Enter 1st number"))

    b = (input("Enter 2nd number"))

    return a+b

print(addition)


<function addition at 0x7a109caedd80>


In [ ]:
def addition():

    a = int(input("Enter 1st number"))

    b = int(input("Enter 2nd number"))

    return (a+b)

print(addition())


Enter 1st number34
Enter 2nd number34
68


In [ ]:
# create a function named as described_ped and provide some parameter that will best describe your pets
#code by om/opiee
def desc_pet():

     pet_name = input('enter the pet name:  ')
     pet_type = input('enter the pet type:  ')
     pet_breed = input('enter the pet breed:  ')
     pet_age = input('enter the pet age:  ')
     pet_color = input('enter the pet color:  ')
     pet_weight = input('enter the pet weight:  ')
     return f"Name = {pet_name}, Type = {pet_type}, Breed = {pet_breed}, Age = {pet_age}, Color = {pet_color}, Weight = {pet_weight}"

print(desc_pet())

enter the pet name:  koki
enter the pet type:  jerman 
enter the pet breed:  sheperd
enter the pet age:  3
enter the pet color:  black
enter the pet weight:  67
Name = koki, Type = jerman , Breed = sheperd, Age = 3, Color = black, Weight = 67


In [ ]:
def add_number():
  num1 = int(input("enter the first number"))
  num2 = int(input("enter the second number"))
  return num1+num2

print(add_number())

enter the first number34
enter the second number43
77


In [ ]:
def describe_pet(pet_name, animal_type, age, color, breed):
    description = f"{pet_name} is a {age}-year-old {color} {animal_type} of the {breed}"

In [ ]:
def addition():
    a = int(input("Enter 1st number"))
    b = int(input("Enter 2nd number"))
    return (a+b)
print(addition())

Enter 1st number67
Enter 2nd number65
132


# **question1**  : Finding the largest number:

In [ ]:
#  finding the largest number using if else statement



a = 10
b = 20
c = 30

if a > b and a > c:
  print(f"{a} is greater")
elif b > a and b > c:
  print(f"{b} is greater")
else:
  print(f"{c} is greater")


30 is greater


In [ ]:
# finding the largest number using if else statement
# code by om/opiee

def find_largest():
  num1 = int(input('enter the first number:  '))
  num2 = int(input('enter the second number:  '))
  num3 = int(input('enter the third number:  '))
  if num1 > num2 and num1 > num3:
    print(f"{num1} is the largest number")
  elif num2 > num1 and num2 > num3:
    print(f"{num2} is the largest number")
  else:
    print(f"{num3} is the largest number")

find_largest()

enter the first number:  6
enter the second number:  16
enter the third number:  160
160 is the largest number


In [ ]:
num1 = float(input("Enter the first number: "))
num2 = float(input("Enter the second number: "))
num3 = float(input("Enter the third number: "))


if (num1 >= num2) and (num1 >= num3):
    largest = num1
elif (num2 >= num1) and (num2 >= num3):
    largest = num2
else:
    largest = num3

print(f"The largest number is: {largest}")

Enter the first number: 4
Enter the second number: 34
Enter the third number: 34
The largest number is: 34.0


In [ ]:
a= int(input("Enter first number:"))
b= int(input("Enter second number:"))
c= int(input("Enter third number:"))
if a>b and a>c:
    print("a is greater")
elif b>a and b>c:
    print("b is greater")
else:
    print("c is greater")

Enter first number:34
Enter second number:43


KeyboardInterrupt: Interrupted by user

# 2Question  sum of list elements

In [ ]:
# create a list  , you sum up the list items present inside the list

In [ ]:
# create a list, you sum up the list items present inside the list
# code by om/opiee

list1 = [1,2,3,4,5]
sum = 0
for i in list1:
  sum += i
print(sum)

In [ ]:
try:
    my_list = [int(i) for i in input("Enter some numbers seperated by commas like '1,2,3'").split(',')]
    sum = 0
    for i in my_list:
        sum += i
    print(sum)
except ValueError:
    print("Invalid input")

Enter some numbers seperated by commas like '1,2,3'1,2,3,4,5
15


In [ ]:
number = [1,2,3,4,5,6,7,8]

total = sum(number)
print(total)

36


In [ ]:
numbers = [10, 20, 30, 40, 50]

total_sum = sum(numbers)

print(f"The sum of the list items is: {total_sum}")


The sum of the list items is: 150


#**question3** creating password

In [ ]:
#   ask the user to enter the pass ,

#  if length is greater tha 6
# password is  valid

In [ ]:
#Password strength checker
import sys
x = input("Enter your password: ")
if len(x)<6:
    print("Password too short")
    sys.exit()
print("Password accepted!")

Enter your password: yueu
Password too short


SystemExit: 

In [ ]:
password = input("Enter your password: ")


if len(password) > 6:
    print("Password is valid.")
else:
    print("Password is too short.")

Enter your password: tyub
Password is too short.


# **question4**: printing start pattern

In [ ]:
#

*
**
***
****

In [ ]:


rows = 4

for i in range(1, rows + 1):

    # Print i stars for each row

    print('*' * i)



*
**
***
****


In [ ]:
try:
    for i in range(0,int(input("Enter the number of stars: "))):
        print("*"*i)
except ValueError:
    print("Invalid input")

Enter the number of stars: 6

*
**
***
****
*****


#**question**  5 : count the occurence of  elements inside the list

In [ ]:
# number =[4,7,1,4,12,4,3]

#count  the occurence of each element

In [ ]:
numbers = [4, 7, 1, 4, 12, 4, 3]
element = 7
occurrences = numbers.count(element)

print(occurrences)


1


:#**question 6 **: finding prime number

In [ ]:
# prime number

In [ ]:
#Sieve of erasthtenes
import numpy
import math
from datetime import datetime
def prime(x):
    nums = numpy.ones(x+1,dtype=bool)
    check = math.isqrt(x) + 1
    nums[0:2] = False
    for i in range(2,check):
        if nums[i]:
            nums[i*i:x+1:i] = False

    for i in range(2,x+1):
        if nums[i]:
            print("{} is prime".format(i))
start_time = datetime.now()
print("Start time =", start_time.strftime("%H:%M:%S"))
prime(int(input("Find till where: ")))
end_time = datetime.now()
print("End time =", end_time.strftime("%H:%M:%S"))
# Calculate time taken
diff = end_time - start_time
print("Time taken: {} seconds".format(diff.total_seconds()))

Start time = 16:53:04
Find till where: 5
2 is prime
3 is prime
5 is prime
End time = 16:53:07
Time taken: 3.094057 seconds


In [ ]:
num = int(input("enter a number"))

if num%2 ==0:
  print(num,"is not prime")
else:
  print(num ,"is prime")


enter a number6
6 is not prime


In [ ]:
# find the occurence of value in my list
# code by om/opiee

number =[4,7,1,4,12,4,3,1,7]
print (number)

element = int(input('find the number of times the value in the list '))

count = 0
for i in number:

  if i == element:
    count += 1
print(count)

[4, 7, 1, 4, 12, 4, 3, 1, 7]
find the number of times the value in the list 7
2


In [ ]:
# a = 10
# b = 20

a  = 20
b = 10

# swap  two variables

In [ ]:
a = 10
b = 20
temp= a
a = b
b = temp
print(f"After swapping: a = {a}, b = {b}")

After swapping: a = 20, b = 10


In [ ]:
a, b = b, a        print(f"After swapping: a = {a}, b = {b}") After swapping: a = 20, b = 10


SyntaxError: invalid syntax (<ipython-input-51-19db0a07fb46>, line 1)

In [ ]:
# asking the user to enter a value
# user enter another value
# swap the value
# code by om/opiee

a = input('enter the value of a:  ')
b = input('enter the value of b:  ')
print (f"before swapping a = {a} and b = {b}")
temp = a
a = b
b = temp
print (f"after swapping a = {a} and b = {b}")


enter the value of a:  3
enter the value of b:  4
before swapping a = 3 and b = 4
after swapping a = 4 and b = 3


In [ ]:
a = 10
b = 20
a,b = b,a

print(f"after swaping the values are {a} and {b}")

after swaping the values are 20 and 10


In [ ]:
pip install numpy


In [ ]:
import numpy as np


x = np.array([1,2,3,4,5])
print(x)

[1 2 3 4 5]


In [ ]:
# 0 Dim
a = np.array(10)
print(a)
print(a.ndim)

10
0


In [ ]:
a = np.array([10,20,30,40,50])
print(a)
print(a.ndim)

[10 20 30 40 50]
1


In [ ]:
a = np.array([[20,30],[40,50]])
print(a)
print(a.ndim)

[[20 30]
 [40 50]]
2


In [ ]:
a=np.array([[[]]])
print(a)
print(a.ndim)

[]
3


In [ ]:
#indexing
list1 = [1,2,3,4,5,6]
a=np.array(list1)
a[1]

2

In [ ]:
#reshape Function
a=np.array([1,2,3,4,5])
b=a.reshape((1,5))
print(b)

[[1 2 3 4 5]]


In [ ]:
#matrix operation
np.full()
np.absnp.operations()
np.zero()
np.identity()
np.eye()

In [ ]:
a = np.full((4,3),8.2)
print(a)

[[8.2 8.2 8.2]
 [8.2 8.2 8.2]
 [8.2 8.2 8.2]
 [8.2 8.2 8.2]]


In [ ]:
a=np.ones((3,2),dtype = int)
print(a)

[[1 1]
 [1 1]
 [1 1]]


In [ ]:
a=np.identity(2)
print(a)

[[1. 0.]
 [0. 1.]]


In [ ]:
#arthmectic operators
a=np.array([1,2])
b=np.array([6,7])

print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a//b)
print(a%b)



[7 9]
[-5 -5]
[ 6 14]


In [ ]:
a=np.array([[1,2],[4,5]])
b=np.array([10,20])
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a//b)
print(a%b)


[[11 22]
 [14 25]]
[[ -9 -18]
 [ -6 -15]]
[[ 10  40]
 [ 40 100]]
[[0.1  0.1 ]
 [0.4  0.25]]
[[0 0]
 [0 0]]


In [ ]:
x=np.sum(a)
print(x)

12


In [ ]:
a=np.array([[1,2,3],[2,3,4]])
print(a)
z=np.sum(a)
print(z)

[[1 2 3]
 [2 3 4]]
15


In [ ]:
a=np.array([[1,2,3],[2,3,4]])
x=np.mean(a)
print(x)

2.5


In [ ]:
sum_axis_0 = np.sum(matrix, axis=0)
print(sum_axis_0)


NameError: name 'matrix' is not defined

In [ ]:
#Std,Mean & STD>Deviation
data = [4, 7, 10, 12, 15]

variance = np.var(data)
print("Variance:", variance)

std_dev = np.std(data)
print("Standard Deviation:", std_dev)



Variance: 14.639999999999997
Standard Deviation: 3.826225293941798


In [ ]:
#Random Function
randint
random
np.linspace
arange


x=np.random.randint(1,100)
print(x)

NameError: name 'randint' is not defined

In [ ]:
x=np.random.randint(1,50)
print(x)

6


In [ ]:
y=np.linspace(0,5,num=20)
print(y)

[0.         0.26315789 0.52631579 0.78947368 1.05263158 1.31578947
 1.57894737 1.84210526 2.10526316 2.36842105 2.63157895 2.89473684
 3.15789474 3.42105263 3.68421053 3.94736842 4.21052632 4.47368421
 4.73684211 5.        ]


In [ ]:
x=np.arange(0,5,1)
print(x)

[0 1 2 3 4]


In [ ]:
import numpy as np

In [ ]:
# numpy hands on 20-Oct-2024
x=np.array([1,2,3,4],dtype=int)
print(x)

[1 2 3 4]


In [ ]:
x=np.array([1,2,3,4],dtype=float)
print(x)

[1. 2. 3. 4.]


In [ ]:
r=np.array(42)
print(r)
print(r.ndim)
r=np.array([1,2,3,4])
print(r)
print(r.ndim)
r=np.array([[1,2],[4,5]])
print(r)
print(r.ndim)
r=np.array([[[1,2],[3,4]],[[4,5],[7,8]]])
print(r)
print(r.ndim)

42
0
[1 2 3 4]
1
[[1 2]
 [4 5]]
2
[[[1 2]
  [3 4]]

 [[4 5]
  [7 8]]]
3


In [ ]:
z=[[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]]
x=np.array(z)
print(x)
print(x.shape)
print(x.ndim)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]]
(1, 4, 3)
3


In [ ]:
#Create a 2x3, 3x3, and 4x4 identity matrix using numpy.

x=np.array([4,5])
print("x -like matrix:")
print(x,identity_2*3)
x=np.array(3)
print("x -like matrix:")
print(identity_3*3)
x=np.array(4)
print("x -like matrix:")
print(identity_4*4)

x -like matrix:


NameError: name 'identity_2' is not defined

In [ ]:
# 3x3 identity matrix
identity_3x3 = np.eye(3)
print("\n3x3 Identity matrix:")
print(identity_3x3)



3x3 Identity matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
x=np.eye(2,3)
print(x)

y=np.eye(3,4)
print(y)

z=np.identity(4)
print(z)

[[1. 0. 0.]
 [0. 1. 0.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
#4. Create a numpy array with shape 2x5 that has all the elements as zero.
#5. Create a numpy array that has the shape 3x5 and all the elements are 5

In [ ]:
x=np.zeros((2,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
import numpy as np

# Creating a 2x5 array filled with zeros
zero_array = np.zeros((2, 5))
print("2x5 array filled with zeros:")
print(zero_array)


2x5 array filled with zeros:
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
x=np.full((3,5),5)
print(x)

[[5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]]


In [ ]:
import numpy as np
a = np.full((2,5),0,dtype=int)
b = np.full((3,5),5,dtype=int)
print(a,b,sep='\n')

[[0 0 0 0 0]
 [0 0 0 0 0]]
[[5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]]


In [ ]:
6.# Create a numpy array with random integers in the range 0-100, and the sample size should be 25

In [ ]:
z=np.random.randint(0,101, size=25)
print(z)

[98 11 94 89 66 37 67 23 53 38 57 26 29 19 66 53 86 26 33 44 73 51 19 46
 31]


In [ ]:
# Create a numpy array with a shape 3x3 that has all elements as 1.
#Create a numpy array in the shape 2x3 with random integers in the range 0-100

In [ ]:
r=np.ones((3,3))
print(r)
r=np.random.randint(0,101, size=(2,3))
print(r)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[ 3 90 36]
 [93 51 53]]


In [ ]:
r=np.random.randint(0,101, size=(2,3))
print(r)

[[ 6 95 66]
 [96  6 94]]


In [ ]:
#Create a random array , with the range 0-1000 with a size 50



In [ ]:
r=np.random.choice(np.arange(0,1001,2),size=50,replace=False)
print(r)
print(r[:10])
print(r[-10:])
print(r[10:26])
print(r[22])
print(r[::-1])
print(r[-10:])

[468 190 262 304 400 372 818 326  82  60 716 366 500 726 502 702 408 720
 690 146 678 298  30 796 892 162 492   8 506 280 808 900 578  94  52 184
 826  56 528 642 232 120 460 788 236 482 708 628 836 334]
[468 190 262 304 400 372 818 326  82  60]
[232 120 460 788 236 482 708 628 836 334]
[716 366 500 726 502 702 408 720 690 146 678 298  30 796 892 162]
30
[334 836 628 708 482 236 788 460 120 232 642 528  56 826 184  52  94 578
 900 808 280 506   8 492 162 892 796  30 298 678 146 690 720 408 702 502
 726 500 366 716  60  82 326 818 372 400 304 262 190 468]
[232 120 460 788 236 482 708 628 836 334]


In [ ]:
#Given a numpy array that has values = [1,2,3,4,5]. Perform the following operations.
a. Insert the element 6 at the end of the array.
b. Insert the element 10 at the beginning of the array.
c. Insert the element 30, before 4.
d. Update the element 5 as 50.
e. Delete the element 50 in the updated array.
f. Create a function to search for the element 30.
g. Sort the array in ascending order.

In [ ]:
r=np.array([1,2,3,4,5])
r=np.append(r,6)
r=np.insert(r,0,10)
r[r==5] = 50
r=np.delete(r,np.where(r==50))
print(r)

def search_element(array, element):
    index = np.where(array == element)
    if index[0].size > 0:
        return f"Element {element} found at index {index[0][0]}"
    else:
        return f"Element {element} not found"

# Searching for element 30
print("\nSearch for element 30:")
print(search_element(arr, 30))

# g. Sort the array in ascending order


[10  1  2  3  4  6]

Search for element 30:


NameError: name 'arr' is not defined

In [ ]:
r = np.sort(r)
print("\nArray after sorting in ascending order:")
print(r)


Array after sorting in ascending order:
[ 1  2  3  4  6 10]


In [ ]:
r=np.insert(r,4,30)
print(r)

[ 1  2  3  4 30  6 10]


In [ ]:
x="hello world"
print(x)


hello world
